name: CI Instrumentation Full

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'instrumentation/opentelemetry-instrumentation-action_mailer/**'
      - 'instrumentation/opentelemetry-instrumentation-action_pack/**'
      - 'instrumentation/opentelemetry-instrumentation-action_view/**'
      - 'instrumentation/opentelemetry-instrumentation-active_job/**'
      - 'instrumentation/opentelemetry-instrumentation-active_model_serializers/**'
      - 'instrumentation/opentelemetry-instrumentation-active_record/**'
      - 'instrumentation/opentelemetry-instrumentation-active_storage/**'
      - 'instrumentation/opentelemetry-instrumentation-active_support/**'
      - 'instrumentation/opentelemetry-instrumentation-aws_sdk/**'
      - 'instrumentation/opentelemetry-instrumentation-aws_lambda/**'
      - 'instrumentation/opentelemetry-instrumentation-base/**'
      - 'instrumentation/opentelemetry-instrumentation-concurrent_ruby/**'
      - 'instrumentation/opentelemetry-instrumentation-delayed_job/**'
      - 'instrumentation/opentelemetry-instrumentation-ethon/**'
      - 'instrumentation/opentelemetry-instrumentation-excon/**'
      - 'instrumentation/opentelemetry-instrumentation-faraday/**'
      - 'instrumentation/opentelemetry-instrumentation-grape/**'
      - 'instrumentation/opentelemetry-instrumentation-graphql/**'
      - 'instrumentation/opentelemetry-instrumentation-grpc/**'
      - 'instrumentation/opentelemetry-instrumentation-gruf/**'
      - 'instrumentation/opentelemetry-instrumentation-http/**'
      - 'instrumentation/opentelemetry-instrumentation-http_client/**'
      - 'instrumentation/opentelemetry-instrumentation-httpx/**'
      - 'instrumentation/opentelemetry-instrumentation-koala/**'
      - 'instrumentation/opentelemetry-instrumentation-lmdb/**'
      - 'instrumentation/opentelemetry-instrumentation-logger/**'
      - 'instrumentation/opentelemetry-instrumentation-net_http/**'
      - 'instrumentation/opentelemetry-instrumentation-rack/**'
      - 'instrumentation/opentelemetry-instrumentation-rails/**'
      - 'instrumentation/opentelemetry-instrumentation-restclient/**'
      - 'instrumentation/opentelemetry-instrumentation-rspec/**'
      - 'instrumentation/opentelemetry-instrumentation-sinatra/**'
      - 'opentelemetry-helpers/**'
      - '.github/workflows/test_ci_cd_ci_instrumentation_2.yml'
      - '.github/actions/**'
      - 'Gemfile'
      - 'Rakefile'
      - '.rubocop.yml'
      - 'gemspecs/**'
  pull_request:
    branches:
      - main
    paths:
      - 'instrumentation/opentelemetry-instrumentation-action_mailer/**'
      - 'instrumentation/opentelemetry-instrumentation-action_pack/**'
      - 'instrumentation/opentelemetry-instrumentation-action_view/**'
      - 'instrumentation/opentelemetry-instrumentation-active_job/**'
      - 'instrumentation/opentelemetry-instrumentation-active_model_serializers/**'
      - 'instrumentation/opentelemetry-instrumentation-active_record/**'
      - 'instrumentation/opentelemetry-instrumentation-active_storage/**'
      - 'instrumentation/opentelemetry-instrumentation-active_support/**'
      - 'instrumentation/opentelemetry-instrumentation-aws_sdk/**'
      - 'instrumentation/opentelemetry-instrumentation-aws_lambda/**'
      - 'instrumentation/opentelemetry-instrumentation-base/**'
      - 'instrumentation/opentelemetry-instrumentation-concurrent_ruby/**'
      - 'instrumentation/opentelemetry-instrumentation-delayed_job/**'
      - 'instrumentation/opentelemetry-instrumentation-ethon/**'
      - 'instrumentation/opentelemetry-instrumentation-excon/**'
      - 'instrumentation/opentelemetry-instrumentation-faraday/**'
      - 'instrumentation/opentelemetry-instrumentation-grape/**'
      - 'instrumentation/opentelemetry-instrumentation-graphql/**'
      - 'instrumentation/opentelemetry-instrumentation-grpc/**'
      - 'instrumentation/opentelemetry-instrumentation-gruf/**'
      - 'instrumentation/opentelemetry-instrumentation-http/**'
      - 'instrumentation/opentelemetry-instrumentation-http_client/**'
      - 'instrumentation/opentelemetry-instrumentation-httpx/**'
      - 'instrumentation/opentelemetry-instrumentation-koala/**'
      - 'instrumentation/opentelemetry-instrumentation-lmdb/**'
      - 'instrumentation/opentelemetry-instrumentation-logger/**'
      - 'instrumentation/opentelemetry-instrumentation-net_http/**'
      - 'instrumentation/opentelemetry-instrumentation-rack/**'
      - 'instrumentation/opentelemetry-instrumentation-rails/**'
      - 'instrumentation/opentelemetry-instrumentation-restclient/**'
      - 'instrumentation/opentelemetry-instrumentation-rspec/**'
      - 'instrumentation/opentelemetry-instrumentation-sinatra/**'
      - 'opentelemetry-helpers/**'
      - '.github/workflows/test_ci_cd_ci_instrumentation_2.yml'
      - '.github/actions/**'
      - 'Gemfile'
      - 'Rakefile'
      - '.rubocop.yml'
      - 'gemspecs/**'
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}  # Ensure that only one instance of this workflow is running per Pull Request
  cancel-in-progress: true  # Cancel any previous runs of this workflow

jobs:
  instrumentation:
    strategy:
      fail-fast: false
      matrix:
        gem:
          - action_mailer
          - action_pack
          - action_view
          - active_job
          - active_model_serializers
          - active_record
          - active_storage
          - active_support
          - aws_sdk
          - aws_lambda
          - base
          - concurrent_ruby
          - delayed_job
          - ethon
          - excon
          - faraday
          - grape
          - graphql
          - grpc
          - gruf
          - http
          - http_client
          - httpx
          - koala
          - lmdb
          - logger
          - net_http
          - rack
          - rails
          - restclient
          - rspec
          - sinatra
        os:
          - ubuntu-latest

    name: ${{ matrix.gem }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: "Test Ruby 3.4"
        run: |
          echo "Testing opentelemetry-instrumentation-${{ matrix.gem }} on Ruby 3.4"
      - name: "JRuby Filter"
        id: jruby_skip
        shell: bash
        run: |
          echo "skip=false" >> $GITHUB_OUTPUT
          [[ "${{ matrix.gem }}" == "action_pack"              ]] && echo "skip=true" >> $GITHUB_OUTPUT
          [[ "${{ matrix.gem }}" == "action_view"              ]] && echo "skip=true" >> $GITHUB_OUTPUT
          [[ "${{ matrix.gem }}" == "active_model_serializers" ]] && echo "skip=true" >> $GITHUB_OUTPUT
          [[ "${{ matrix.gem }}" == "active_record"            ]] && echo "skip=true" >> $GITHUB_OUTPUT
          [[ "${{ matrix.gem }}" == "active_storage"           ]] && echo "skip=true" >> $GITHUB_OUTPUT
          [[ "${{ matrix.gem }}" == "active_support"           ]] && echo "skip=true" >> $GITHUB_OUTPUT
          [[ "${{ matrix.gem }}" == "aws_sdk"                  ]] && echo "skip=true" >> $GITHUB_OUTPUT
          [[ "${{ matrix.gem }}" == "aws_lambda"               ]] && echo "skip=true" >> $GITHUB_OUTPUT
          [[ "${{ matrix.gem }}" == "delayed_job"              ]] && echo "skip=true" >> $GITHUB_OUTPUT
          [[ "${{ matrix.gem }}" == "graphql"                  ]] && echo "skip=true" >> $GITHUB_OUTPUT
          [[ "${{ matrix.gem }}" == "http"                     ]] && echo "skip=true" >> $GITHUB_OUTPUT
          [[ "${{ matrix.gem }}" == "http_client"              ]] && echo "skip=true" >> $GITHUB_OUTPUT
          [[ "${{ matrix.gem }}" == "koala"                    ]] && echo "skip=true" >> $GITHUB_OUTPUT
          [[ "${{ matrix.gem }}" == "lmdb"                     ]] && echo "skip=true" >> $GITHUB_OUTPUT
          [[ "${{ matrix.gem }}" == "rack"                     ]] && echo "skip=true" >> $GITHUB_OUTPUT
          [[ "${{ matrix.gem }}" == "rails"                    ]] && echo "skip=true" >> $GITHUB_OUTPUT
          [[ "${{ matrix.gem }}" == "grpc"                     ]] && echo "skip=true" >> $GITHUB_OUTPUT
          [[ "${{ matrix.gem }}" == "gruf"                     ]] && echo "skip=true" >> $GITHUB_OUTPUT
          # This is essentially a bash script getting evaluated, so we need to return true or the whole job fails.
          true
      - name: "Test JRuby"
        if: "${{ matrix.os == 'ubuntu-latest' && steps.jruby_skip.outputs.skip == 'false' }}"
        run: |
          echo "Testing opentelemetry-instrumentation-${{ matrix.gem }} on JRuby"
